# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_eintrag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eintrag',
            name='eintrag',
        ),
    ]
